version: '3.3'
services:


  # docker run -d --name redis -p 6700:6379 redis:latest
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6700:6700
    networks:
      - backend

  controller:
    container_name: controller
    command: bash -c "python3 -u ctrl.py"
    build: .
    ports:
      - 8080:8080 
    # env_file:
    #   - .env

    networks:
      - backend

  api:
    container_name: api
    command: bash -c "uvicorn api:app --host 0.0.0.0 --port 5000"
    build: .
    ports:
      - 5000:5000
    networks:
      - backend


  worker:
    container_name: worker
    command: bash -c "python3 -u worker.py"
    build: .

    networks:
      - backend

networks:
  backend:
    driver: "bridge"
